---

- block:
    - name: guess who am I
      shell: whoami
      register: whoami
      changed_when: no
      check_mode: no

    - name: get my homedir
      shell: "getent passwd {{ whoami.stdout }} | awk -F: '{print $6 }'"
      changed_when: no
      register: whoami_homedir

    - name: set nodejs_base_dir
      set_fact:
        nodejs_base_dir: "{{ whoami_homedir.stdout }}/{{ nodejs_local_dir }}/"

  when: nodejs_base_dir is not defined or nodejs_base_dir == ""

- name: install nodejs
  include: install_nodejs.yml

- name: install yarn
  include: install_yarn.yml

- name: update profile
  include: update_profile.yml
